### ISSUE TITLE
docker-compose update for deploy

### ISSUE THREAD

**Issue by ristes** [Miroslav2010/masters-application-system#21]
udpate the docker-compose.yml to the following content:
```
version: '2'

services:
  master-thesis-app:
    image: 'application.jar:latest'
    build:
      context: .
    container_name: master-thesis-app
    ports:
      - "9010:8080"
    depends_on:
      - master-thesis-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://master-thesis-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod

  master-thesis-db:
    image: 'postgres:13.1-alpine'
    container_name: master-thesis-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

```
